# KNN Predict weather a person will have a diabetes or not

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
name=['sepal.length', 'sepal.width', 'petal.length','petal.width','variety']

In [15]:
dataset=pd.read_csv(r'C:\Users\Sonu\Desktop\KNN\8836201-6f9306ad21398ea43cba4f7d537619d0e07d5ae3\iris.csv')

In [16]:
dataset.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [24]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,4].values

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [41]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_train=scaler.transform(X_train)

In [49]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [54]:
Y_pred=classifier.predict(X_test)

In [72]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      1.00      1.00        12
   Virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[ 8  0  0]
 [ 0 12  0]
 [ 0  0 10]]
